routes/main.py
import csv
import pandas as pd
from flask import Blueprint, render_template, redirect, url_for, request, flash
from flask_login import login_required, current_user
from forms import RequestForm
from models.models import Request
from solveform import SolveForm
from solver import solve
from extensions import db
from models.models import User
from datetime import datetime


main = Blueprint('main', __name__)

@main.route('/')
def index():
    return redirect(url_for('auth.login'))


@main.route('/dashboard')
@login_required
def dashboard():
    return render_template('dashboard.html', name=current_user.name)


@main.route('/form', methods=['GET', 'POST'])
@login_required
def form():
    request_form = RequestForm()
    if request.method == 'POST' and request_form.validate():
        if request_form.validate():
            request_type = request_form.type.data
            start_location = request_form.start_location.data
            end_location = request_form.end_location.data
            departure_time = request_form.departure_time.data
            if request_type == 'rider':
                pet = request_form.pet_preference.data
                smoker = request_form.smoker_preference.data
                disable = request_form.disable_preference.data
                seats = None  # Define seats as None for rider requests
            else:
                seats = int(request_form.seats.data)
                pet = request_form.car_pet_friendly.data
                smoker = request_form.car_smoker_friendly.data
                disable = request_form.car_disable_access.data

            start_lat, start_long = None, None
            end_lat, end_long = None, None
            # Fetch latitude and longitude from the file
            with open('updated_file.csv', 'r') as f:
                reader = csv.DictReader(f)
                for row in reader:
                    if row['postcode'] == start_location:
                        start_lat, start_long = float(row['Latitude']), float(row['Longitude'])
                    if row['postcode'] == end_location:
                        end_lat, end_long = float(row['Latitude']), float(row['Longitude'])

            if start_lat is None or start_long is None:
                flash(f'Could not find start location: {start_location}')
                return redirect(url_for('main.form'))

            if end_lat is None or end_long is None:
                flash(f'Could not find end location: {end_location}')
                return redirect(url_for('main.form'))

            request_entry = Request(
                user_id=current_user.id,
                type=request_type,
                start_location=start_location,
                start_lat=start_lat,
                start_long=start_long,
                end_location=end_location,
                end_lat=end_lat,
                end_long=end_long,
                departure_time=departure_time,
                seats=seats,
                pet=pet,
                smoker=smoker,
                disable=disable
            )

            print("Before adding to session:", db.session.new)
            db.session.add(request_entry)
            print("After adding to session:", db.session.new)
            db.session.commit()

            flash('Your request has been submitted!', 'success')
            return redirect(url_for('main.dashboard'))
    else:
        for field, errors in request_form.errors.items():
            for error in errors:
                flash(error, 'error')

    return render_template('request_form.html', form=request_form)


from datetime import date


@main.route('/solve', methods=['GET', 'POST'])
@login_required
def solve_route():
    result = None
    today = date.today()
    current_time = datetime.now()
    if request.method == 'POST':
        print("Inside solve_route function")
        tolerance = 1

        # Fetch data from SQL database
        drivers_data = db.session.query(Request, User).join(User, User.id == Request.user_id).filter(
            Request.type == 'driver', Request.departure_time >= today).all()
        riders_data = db.session.query(Request, User).join(User, User.id == Request.user_id).filter(
            Request.type == 'rider', Request.departure_time >= today).all()
        shifters_data = db.session.query(Request, User).join(User, User.id == Request.user_id).filter(
            Request.type == 'shifter', Request.departure_time >= today).all()

        # Convert data into dictionaries and add the user's name
        drivers_dict = [{**driver[0].to_dict(), "name": driver[1].name} for driver in drivers_data]
        riders_dict = [{**rider[0].to_dict(), "name": rider[1].name} for rider in riders_data]
        shifters_dict = [{**shifter[0].to_dict(), "name": shifter[1].name} for shifter in shifters_data]

        if drivers_dict or riders_dict or shifters_dict:
            result = solve(tolerance, drivers_dict, riders_dict, shifters_dict)
            print("Solving process completed")

        if not result:
            flash('We are sorry; there is currently no matching request found.', 'error')

        return render_template('solve_form.html', results=result, current_time=current_time)

    form = SolveForm()
    return render_template('solve_form.html', form=form, current_time=current_time)

templates/About.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/car.css') }}">
</head>
</html>

templates/dashboard.html
<!DOCTYPE html>
<html>
<head>
    <title>Dashboard</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/button1.css') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/dash.css') }}">
    <link rel="stylesheet" type="text/js" href="{{ url_for('static', filename='js/dash.js') }}">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/button2.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans|Maven+Pro:500' rel='stylesheet' type='text/css'>
    <style>
body {
            display: flex;
            flex-direction: column;
            min-height: 100vh;
            margin: 0;
        }

        #content-container {
            flex: 1;
            display: flex;
            align-items: center;
            justify-content: center;
            flex-direction: column;
        }

        /* Additional CSS to center the buttons horizontally */
        #content-container button {
            margin-top: 10px;
        }
        section {
    float: left;
    width: 100%;
    position: relative;
    box-shadow: 0 0 5px 0px #333;
    background: none; /* Updated: Set background to none */
}


        /* the important styles */
        .arrow-wrap {
            position: absolute;
            z-index: 1;
            left: 50%;
            top: -25em;
            margin-left: -5em;
            background: #111;
            width: 10em;
            height: 10em;
            padding: 4em 2em;
            border-radius: 50%;
            font-size: 0.5em;
            display: block;
            box-shadow: 0px 0px 5px 0px #333;
        }

        .arrow {
            float: left;
            position: relative;
            width: 0px;
            height: 0px;
            border-style: solid;
            border-width: 3em 3em 0 3em;
            border-color: #ffffff transparent transparent transparent;
            -webkit-transform: rotate(360deg);
        }

        .arrow:after {
            content: '';
            position: absolute;
            top: -3.2em;
            left: -3em;
            width: 0px;
            height: 0px;
            border-style: solid;
            border-width: 3em 3em 0 3em;
            border-color: #111 transparent transparent transparent;
            -webkit-transform: rotate(360deg);
        }

        .hint {
            position: absolute;
            top: 0.6em;
            width: 100%;
            left: 0;
            font-size: 2em;
            font-style: italic;
            text-align: center;
            color: #fff;
            opacity: 0;
        }

        .arrow-wrap:hover .hint {
            opacity: 1;
        }

        @-webkit-keyframes arrows {
            0% { top: 0; }
            10% { top: 12%; }
            20% { top: 0; }
            30% { top: 12%; }
            40% { top: -12%; }
            50% { top: 12%; }
            60% { top: 0; }
            70% { top: 12%; }
            80% { top: -12%; }
            90% { top: 12%; }
            100% { top: 0; }
        }

        .arrow-wrap .arrow {
            -webkit-animation: arrows 2.8s 0.4s;
            -webkit-animation-delay: 3s;
        }
    </style>
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
    <script>
        //this is where we apply opacity to the arrow
        $(window).scroll(function() {
            //get scroll position
            var topWindow = $(window).scrollTop();
            //multiply by 1.5 so the arrow will become transparent half-way up the page
            var topWindow = topWindow * 1.5;
            //get height of window
            var windowHeight = $(window).height();
            //set position as percentage of how far the user has scrolled
            var position = topWindow / windowHeight;
            //invert the percentage
            position = 1 - position;
            //define arrow opacity based on how far up the page the user has scrolled
            //no scrolling = 1, half-way up the page = 0
            $('.arrow-wrap').css('opacity', position);
        });

        $(function() {
            $('a[href*=#]:not([href=#])').click(function() {
                if (location.pathname.replace(/^\//, '') == this.pathname.replace(/^\//, '') && location.hostname == this.hostname) {
                    var target = $(this.hash);
                    target = target.length ? target : $('[name=' + this.hash.slice(1) + ']');
                    if (target.length) {
                        $('html,body').animate({
                            scrollTop: target.offset().top
                        }, 1000);
                        return false;
                    }
                }
            });
        });
    </script>
</head>
{% with messages = get_flashed_messages(with_categories=true) %}
{% if messages %}
    <ul class=flashes>
    {% for category, message in messages %}
        <li class="{{ category }}">{{ message }}</li>
    {% endfor %}
    </ul>
{% endif %}
{% endwith %}<body>
<div id="content-container">
  <h1>Welcome, {{ current_user.name }}!</h1>
  <a class="button" href="{{ url_for('main.form') }}">Create a new request</a>

  <form action="{{ url_for('main.solve_route') }}" method="POST">
    <button data-text="Awesome" class="button2">
      <span class="actual-text">&nbsp;Results&nbsp;</span>
    <span class="hover-text" aria-hidden="true">&nbsp;Results&nbsp;</span>
    </button>
  </form>
</div>


    <div id="image-container">
        <img src="{{ url_for('static', filename='image12_2.png') }}">
    </div>
    <section class="main">
        <a class="arrow-wrap" href="#content">
            <span class="arrow"></span>
        </a>

        <div class="content" id="content">
            <h1>The innovative hub for all your ride-sharing needs!</h1>
            <p>Connect, Collaborate, and Commute! That's our mantra , a state-of-the-art platform that brings drivers, riders, and shifters together in a unique and impactful way. Our website is designed to revolutionize the way you travel, offering a simple, effective, and eco-friendly solution to modern commuting challenges.</p>
            <p>Are you a driver planning a journey from point A to point B? Or perhaps you're a rider searching for a reliable transport option to your desired location? Maybe you're a shifter, able to switch between the roles of driver and rider as needed? Whichever you are, This is the place for you!</p>
            <p>Our unique constraint model works tirelessly to find the perfect match for your travel needs. Simply enter your details, submit your request, and our algorithm will do the rest. The result? A list of potential ride matches displayed directly on your screen.</p>
            <h2>Environment is at our heart. </h2>
            <p>
But we are more than just a ride-matching service. It's a community of environmentally-conscious individuals who understand that sharing a ride can make a world of difference. By choosing to share your commute, you're not only saving on fuel costs and reducing traffic congestion, but you're also playing a significant part in lowering carbon emissions.
            </p>
            <h3>We're driving change, together!</h3>
        </div>
    </section>
</body>
</html>

templates/index.html
<!--<!DOCTYPE html>-->
<!--<html lang="en">-->
<!--<head>-->
<!--    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>-->
<!--    <meta charset="UTF-8">-->
<!--    <meta name="viewport" content="width=device-width, initial-scale=1.0">-->
<!--    <meta http-equiv="X-UA-Compatible" content="ie=edge">-->
<!--    <title>Sign Up</title>-->

<!--    &lt;!&ndash; Font Icon &ndash;&gt;-->
<!--    <link rel="stylesheet" href="static/fonts/material-icon/css/material-design-iconic-font.min.css">-->

<!--    &lt;!&ndash; Main css &ndash;&gt;-->
<!--    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">-->
<!--</head>-->
<!--<body>-->

<!--    <div class="main">-->

<!--        &lt;!&ndash; Sign up form &ndash;&gt;-->
<!--        <section class="signup">-->
<!--            <div class="container">-->
<!--                <div class="signup-content">-->
<!--                    <div class="signup-form">-->
<!--                        <h2 class="form-title">Sign up</h2>-->
<!--                        <form method="POST" class="register-form" id="register-form" action="{{ url_for('auth.signup') }}">-->
<!--                            <div class="form-group">-->
<!--                                <label for="name"><i class="zmdi zmdi-account material-icons-name"></i></label>-->
<!--                                <input type="text" name="name" id="name" placeholder="Your Name"/>-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <label for="email"><i class="zmdi zmdi-email"></i></label>-->
<!--                                <input type="email" name="email" id="email" placeholder="Your Email"/>-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <label for="pass"><i class="zmdi zmdi-lock"></i></label>-->
<!--                                <input type="password" name="password" id="pass" placeholder="Password"/>-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <input type="checkbox" name="agree-term" id="agree-term" class="agree-term" />-->
<!--                                <label for="agree-term" class="label-agree-term"><span><span></span></span>I agree all statements in  <a href="#" class="term-service">Terms of service</a></label>-->
<!--                            </div>-->
<!--                            <div class="form-group form-button">-->
<!--                                <input type="submit" name="signup" id="signup" class="form-submit" value="Register"/>-->
<!--                            </div>-->
<!--                        </form>-->
<!--                    </div>-->
<!--                    <div class="signup-image">-->
<!--                        <figure><img src="static/images/signup-image.jpg" alt="sing up image"></figure>-->
<!--                        <a href="{{ url_for('auth.login') }}" class="register-form">I am already member</a>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </section>-->

<!--        &lt;!&ndash; Sing in  Form &ndash;&gt;-->
<!--        <section class="sign-in">-->
<!--            <div class="container">-->
<!--                <div class="signin-content">-->
<!--                    <div class="signin-image">-->
<!--                        <figure><img src="static/images/signin-image.jpg" alt="sing up image"></figure>-->
<!--                        <a href="#" class="signup-image-link">Create an account</a>-->
<!--                    </div>-->

<!--                    <div class="signin-form">-->
<!--                        <h2 class="form-title">Login</h2>-->
<!--                        <form method="POST" class="register-form" id="Log In" action="{{ url_for('auth.login') }}">-->
<!--                            <div class="form-group">-->
<!--                                <label for="your_pass"><i class="zmdi zmdi-lock"></i></label>-->
<!--                                <input type="password" name="your_pass" id="your_pass" placeholder="Password"/>-->
<!--                            </div>-->
<!--                            <div class="form-group">-->
<!--                                <input type="checkbox" name="remember-me" id="remember-me" class="agree-term" />-->
<!--                                <label for="remember-me" class="label-agree-term"><span><span></span></span>Remember me</label>-->
<!--                            </div>-->
<!--                            <div class="form-group form-button">-->
<!--                                <input type="submit" name="signin" id="signin" class="form-submit" value="Log in"/>-->
<!--                            </div>-->
<!--                        </form>-->
<!--                    </div>-->
<!--                </div>-->
<!--            </div>-->
<!--        </section>-->

<!--    </div>-->

<!--    &lt;!&ndash; JS &ndash;&gt;-->
<!--    <script src="static/vendor/jquery/jquery.min.js"></script>-->
<!--    <script src="static/js/main.js"></script>-->

<!--<script>-->
<!--$(document).ready(function(){-->
<!--    $(".signup-image-link").click(function(){-->
<!--        $(".sign-in").show();-->
<!--        $(".signup").hide();-->
<!--    });-->
<!--    $(".form-title").click(function(){-->
<!--        $(".signup").show();-->
<!--        $(".sign-in").hide();-->
<!--    });-->
<!--});-->
<!--</script>-->

<!--</body>-->
<!--</html>-->

templates/login.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/login.css') }}">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Geologica:wght@500&display=swap" rel="stylesheet">
    <style>
    .error-messages {
      color: red;
    }
  </style>
</head>
<body>
<h1>
	Escape the Crowd _ _ _ _ _ , Embrace the Ride-Sharing Adventures to
	<span>
		<span>Bath</span>
		<span>London</span>
		<span>Wales</span>
		<span>Scotland</span>
		<span>and many more!</span>
	</span>
</h1>
  <canvas id="canvas"></canvas>
<div class="container">
    <svg class="loader" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 80 80">
      <g class="car">
          <path d="M73.1,53.47V46.4a4.9,4.9,0,0,0-4.9-4.89H56.45l-7.59-9.25a4.08,4.08,0,0,0-3.22-1.59H22.83a4.12,4.12,0,0,0-3.66,2.22v0L15,41.51H11.18a3.94,3.94,0,0,0-3.94,3.94v7.8A2,2,0,0,0,6.15,55v1.81a2,2,0,0,0,2,2H71.87a2,2,0,0,0,2-2V55A2,2,0,0,0,73.1,53.47Zm-65,3.78a.42.42,0,0,1-.42-.42V55a.42.42,0,0,1,.42-.42H20.69v.71H17.06l-2,0c-.65,0-1.3,0-1.95.05a.55.55,0,0,0,0,1.09c.65,0,1.3,0,1.95.05l2,0H21c1.31,0,2.61,0,3.92-.07s2.61-.13,3.91-.28a.27.27,0,0,0,0-.53c-1.3-.15-2.61-.23-3.91-.28-.88,0-1.76,0-2.64-.05V54.6H55.44v.72q-1.26,0-2.52.06c-1.05,0-2.09.13-3.14.28a.27.27,0,0,0-.22.23.26.26,0,0,0,.22.3c1,.15,2.09.23,3.14.28s2.09.05,3.13.07h5.68c1,0,2.09,0,3.13-.07S67,56.34,68,56.19a.27.27,0,0,0,.22-.23.25.25,0,0,0-.22-.3c-1-.15-2.09-.23-3.14-.28s-2.09-.05-3.13-.07H57v-.7H71.87a.42.42,0,0,1,.42.42v1.81a.42.42,0,0,1-.42.42Zm3-14.19h9.51V53H8.8V51.28h2.77a.78.78,0,0,0,.78-.78v-5a.77.77,0,0,0-.78-.77H8.91A2.38,2.38,0,0,1,11.18,43.06ZM22.83,32.23H45.64a2.53,2.53,0,0,1,2,1l0,0,6.79,8.27h-1.8l-6.3-7.64a1.39,1.39,0,0,0-1.1-.54H22.83a1.49,1.49,0,0,0-1.3.79l0,.06-3.14,7.33H16.74l3.82-7.91A2.56,2.56,0,0,1,22.83,32.23Zm15.44,9.28V34.89h6.89l5.47,6.62Zm-1.56,0H25.05V34.89H36.71Zm-13.21,0H20.06l2.83-6.62h.61Zm-1.25,1.55H36.71V53H22.25Zm16,0h15l.93,1.68L55.44,47V53H38.27Zm32.94,3h-2a.47.47,0,0,1-.47-.46V43.43A3,3,0,0,1,71.21,46Zm-2.6,1.87h2.93V53H57V46.78a.79.79,0,0,0-.1-.37l-1.84-3.35H66.9V46.2A1.71,1.71,0,0,0,68.61,47.91ZM10.79,49.72h-2v-.59h1a.39.39,0,0,0,.39-.39V47.26a.38.38,0,0,0-.39-.38h-1v-.6h2Z"/><path d="M42.67,44.37H40.25a.78.78,0,0,0,0,1.56h2.42a.78.78,0,0,0,0-1.56Z"/><path d="M28.83,37.49c.33.39.68.77,1,1.13a13.8,13.8,0,0,0,1.13,1,8.81,8.81,0,0,0,1.27.9.15.15,0,0,0,.13,0,.14.14,0,0,0,.06-.18,10.84,10.84,0,0,0-.9-1.28c-.33-.39-.67-.77-1-1.13s-.74-.7-1.14-1a8.81,8.81,0,0,0-1.27-.9A.15.15,0,0,0,28,36a.13.13,0,0,0,0,.19A9.61,9.61,0,0,0,28.83,37.49Z"/>
          <path d="M27.85,39.62a6.17,6.17,0,0,0,.48.54,4.2,4.2,0,0,0,.54.48,3,3,0,0,0,.63.38h.07a.09.09,0,0,0,.05-.12,3.38,3.38,0,0,0-.38-.64c-.15-.19-.31-.37-.47-.54a4.13,4.13,0,0,0-.55-.47,2.64,2.64,0,0,0-.63-.38s-.05,0-.07,0a.09.09,0,0,0-.05.12A3.3,3.3,0,0,0,27.85,39.62Z"/>
          <path d="M31.15,36.32a6.17,6.17,0,0,0,.48.54,4.78,4.78,0,0,0,.54.47,3.33,3.33,0,0,0,.63.39h.08a.11.11,0,0,0,0-.13,2.85,2.85,0,0,0-.38-.63,6.06,6.06,0,0,0-.47-.54,4.78,4.78,0,0,0-.54-.47,3.42,3.42,0,0,0-.64-.39.09.09,0,0,0-.07,0,.1.1,0,0,0-.05.13A3.64,3.64,0,0,0,31.15,36.32Z"/>
          <path d="M43.86,39.2a13.82,13.82,0,0,0-1-1.14c-.37-.36-.75-.7-1.15-1a8,8,0,0,0-1.3-.87.19.19,0,0,0-.15,0,.17.17,0,0,0-.06.22,8.13,8.13,0,0,0,.86,1.3,12.32,12.32,0,0,0,1,1.14,13.94,13.94,0,0,0,1.14,1,7.92,7.92,0,0,0,1.3.86.16.16,0,0,0,.15,0,.16.16,0,0,0,.07-.21A8.51,8.51,0,0,0,43.86,39.2Z"/>
          <path d="M44,36.14a3.25,3.25,0,0,0-.82-.45h-.1a.16.16,0,0,0-.09.18,4,4,0,0,0,.45.82A5.22,5.22,0,0,0,44.71,38a4,4,0,0,0,.82.45.17.17,0,0,0,.1,0,.15.15,0,0,0,.08-.19,3.57,3.57,0,0,0-.44-.82,5.43,5.43,0,0,0-.59-.68A5.35,5.35,0,0,0,44,36.14Z"/>
          <path d="M31.22,55.61H29.78a.32.32,0,0,0,0,.63h1.44a.32.32,0,0,0,0-.63Z"/>
          <path d="M70.42,55.61H69a.32.32,0,0,0,0,.63h1.44a.32.32,0,0,0,0-.63Z"/>
          <path d="M48.8,55.61H47.36a.32.32,0,0,0,0,.63H48.8a.32.32,0,0,0,0-.63Z"/>
      </g>
      <g class="wheel back-wheel">
      <circle cx="18" cy="56" r="6.75"/>
      <circle class="wheel-details" cx="18." cy="56" r="3.12"/>
      <circle cx="18" cy="56" r="1.85"/>
      <path class="wheel-details" d="M18.05,51.11a4.39,4.39,0,0,1,2,.26l.47.21.45.25.41.31.39.34a4.92,4.92,0,0,1,1.1,1.71,4.42,4.42,0,0,1,.27,2,.15.15,0,0,1-.16.13.16.16,0,0,1-.13-.13h0a5.73,5.73,0,0,0-.49-1.79,5.05,5.05,0,0,0-1-1.48,5.33,5.33,0,0,0-1.49-1,5.86,5.86,0,0,0-1.78-.48h0a.15.15,0,0,1-.13-.16A.14.14,0,0,1,18.05,51.11Z"/>
      </g>

      <g class="wheel front-wheel">
      <circle cx="59" cy="56" r="6.75"/>
      <circle class="wheel-details" cx="59" cy="56" r="3.12"/>
      <circle cx="59" cy="56" r="1.85"/>
      <path class="wheel-details" d="M59.27,51.11a4.39,4.39,0,0,1,2,.26l.47.21.44.25.42.31.38.34a5,5,0,0,1,1.11,1.71,4.56,4.56,0,0,1,.26,2,.14.14,0,0,1-.16.13.16.16,0,0,1-.13-.13h0a5.71,5.71,0,0,0-.48-1.79,5.28,5.28,0,0,0-1-1.48,5.14,5.14,0,0,0-1.48-1,6,6,0,0,0-1.78-.48h0a.14.14,0,0,1-.12-.16A.13.13,0,0,1,59.27,51.11Z"/>
      </g>

      <line class="line line-1"  x1="77" y1="37" x2="4" y2="37"/>
      <line class="line line-2" x1="77" y1="49" x2="4" y2="49"/>
      <line class="line line-floor" x1="76.5" y1="62.43" x2="3.5" y2="62.43"/>
      <path class="cloud" d="M71,26.15a3.37,3.37,0,0,0-3.29-2.65,2.11,2.11,0,0,0-.36,0,5,5,0,0,0-9.73,1.32,3.75,3.75,0,0,0-.82-.09,3.83,3.83,0,0,0-.08,7.65H70.87A3.13,3.13,0,0,0,71,26.15Z"/>
    </svg>
  </div>
  <form class="login" method="post">
    <input type="text" placeholder="Username" name="email">
    <input type="password" placeholder="Password" name="password">
    <button type="submit">Login</button>
    <button type="button" onclick="location.href='{{ url_for('auth.signup') }}'">Register</button>
      {% with messages = get_flashed_messages(category_filter='error') %}
  {% if messages %}
    <div class="error-messages">
      {% for message in messages %}
        <p>{{ message }}</p>
      {% endfor %}
    </div>
  {% endif %}
{% endwith %}
  </form>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.9.1/gsap.min.js"></script>
  <script src="{{ url_for('static', filename='main.js') }}"></script>
</body>
</html>

templates/signup.html
<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/signup.css') }}">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
</head>
<body>
     <img id="car" src="{{ url_for('static', filename='image.png') }}">
     <form id="signupForm" action="{{ url_for('auth.signup') }}" method="post">
        <div id="nameField" class="inputField">
            <label for="name">What's your name?</label>
            <input type="text" id="name" name="name" class="animated-input">
            <button type="button" class="next animated-button">&#8594;</button>
        </div>
        <div id="emailField" class="inputField">
            <label for="email">What's your email?</label>
            <input type="email" id="email" name="email" class="animated-input">
            <button type="button" class="next animated-button">&#8594;</button>
        </div>
        <div id="passwordField" class="inputField">
            <label for="password">What's your password?</label>
            <input type="password" id="password" name="password" class="animated-input">
            <button type="submit" class="next animated-button">&#8594;</button>
            <input type="checkbox" id="showPassword"> Show Password
        </div>
    </form>
    <script>
        var loginUrl = "{{ url_for('auth.login') }}";
    </script>
     <script src="{{ url_for('static', filename='js/signup.js') }}"></script>
</body>
</html>

templates/solve_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Result</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/test.css') }}">
</head>
<body>
 <div class="card">
      <p class="card-title">Matching Results till {{ current_time.strftime('%H:%M %B %d, %Y') }}</p>
      <div class="small-desc">
    <p>
        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
            <div class="mt-4">
                {% for category, message in messages %}
                    <div class="alert alert-{{ category }}">{{ message }}</div>
                {% endfor %}
            </div>
        {% endif %}
        {% endwith %}
    </p>
            {% if results %}
            <ul>
                {% for result in results %}
                    <li>{{ result }}</li>
                {% endfor %}
            </ul>
        {% endif %}
      </div>
    </div>
</body>
</html>